/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_pdf_creator (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);

CREATE TABLE users_pdf_creator (
  id TEXT NOT NULL PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  name TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);
*/

// View at https://supabase.com/dashboard/project/yqrtpnnnirjaopwbmzoi/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () => createClient(
  Deno.env.get("SUPABASE_URL"),
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),
);

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_pdf_creator").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_pdf_creator").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_pdf_creator").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_pdf_creator").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_pdf_creator").select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_pdf_creator").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_pdf_creator").select("key, value").like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  return data ?? [];
};

// ============================================
// USERS TABLE FUNCTIONS (Custom Authentication)
// ============================================

export const createUser = async (email: string, password: string, name?: string): Promise<any> => {
  const supabase = client();
  const id = `user-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
  
  const { data, error } = await supabase.from("users_pdf_creator").insert({
    id,
    email,
    password, // En producción, deberías hashear esto
    name,
  }).select().single();
  
  if (error) {
    throw new Error(error.message);
  }
  
  return data;
};

export const getUserByEmail = async (email: string): Promise<any> => {
  const supabase = client();
  const { data, error } = await supabase.from("users_pdf_creator").select("*").eq("email", email).maybeSingle();
  
  if (error) {
    throw new Error(error.message);
  }
  
  return data;
};

export const getUserById = async (id: string): Promise<any> => {
  const supabase = client();
  const { data, error } = await supabase.from("users_pdf_creator").select("*").eq("id", id).maybeSingle();
  
  if (error) {
    throw new Error(error.message);
  }
  
  return data;
};

export const getUsersSummary = async (): Promise<{ count: number; ids: string[] }> => {
  const supabase = client();
  const { data, error, count } = await supabase
    .from("users_pdf_creator")
    .select("id", { count: "exact" })
    .limit(5);

  if (error) {
    throw new Error(error.message);
  }

  return {
    count: count ?? 0,
    ids: (data ?? []).map((user) => user.id),
  };
};
